WARNING: The Ant PMC link:https://lists.apache.org/thread/wo32q8s8o8z9m126gz3m533q2fnqq21o[voted] to archive the IvyDE subproject. This means that all its resources are removed or made read only and no further development will be done.

NOTE: It also means that, if a community grows, the subproject could
be link:https://ant.apache.org/processes.html#Reactivate%20a%20subproject%20or%20component[reactivated].

= Apache IvyDE


== Supported Platforms

IvyDE expects to run in a specific environment, please check the link:doc/src/compatibility{outfilesuffix}[documentation]


== Installation

For most users who have access to the internet it is easiest to install the latest release from the IvyDE update site. So just look out there:
http://ant.apache.org/ivy/ivyde/download.cgi

If you want to install the zip distribution manually, see the link:doc/src/install{outfilesuffix}[instructions]


== Getting Started

For an introduction to Apache IvyDE and how to use it, please read the link:doc/src/index{outfilesuffix}[documentation]
located in the `doc/src` subdirectory


== Licensing

This software is licensed under the terms you may find in the file named link:LICENSE["LICENSE"] in this directory


== Building

To be able to build IvyDE yourself, please read the relevant link:doc/src/dev/build{outfilesuffix}[documentation]
