////
   Licensed to the Apache Software Foundation (ASF) under one
   or more contributor license agreements.  See the NOTICE file
   distributed with this work for additional information
   regarding copyright ownership.  The ASF licenses this file
   to you under the Apache License, Version 2.0 (the
   "License"); you may not use this file except in compliance
   with the License.  You may obtain a copy of the License at

     https://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing,
   software distributed under the License is distributed on an
   "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
   KIND, either express or implied.  See the License for the
   specific language governing permissions and limitations
   under the License.
////

== [[latest]]Install the last release via Internet

For most users who have access to the internet it is easiest to install the latest release from the Apache IvyDE update site. So just look out there:
https://ant.apache.org/ivy/ivyde/download.cgi

== [[manual]]Manual install

=== Install Apache IvyDE

You should have the zip distribution of Apache IvyDE in which you should find these files:

* features/org.apache.ivyde.feature_2.3.0.XXXX.jar
* plugins/org.apache.ivyde.eclipse_2.3.0.XXXX.jar

You can then install them by unpacking the distribution in `$ECLIPSE_HOME/dropins` directory.
For more information, please see link:https://wiki.eclipse.org/Equinox/p2/Getting_Started[Equinox/p2] documentation.

=== Install the latest Apache Ivy bundle

Get the latest Apache Ivy build for the updatesite:

* the link:https://builds.apache.org/view/All/job/IvyDE-updatesite/lastSuccessfulBuild/artifact/trunk/build/[latest successful build]

Then unpack the zip file and use as local update site.

=== Restart Eclipse

After installing your plugins manually, you have to restart your Eclipse to have it take into account the changes. It is recommended to restart it with the `-clean` option on the command line.
